project_name: komiser
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    dir: ./server/
    main: ./
    ldflags:
      - -X github.com/flemzord/komiser/cmd.BuildDate={{ .Date }}
      - -X github.com/flemzord/komiser/cmd.Version={{ .Version }}
      - -X github.com/flemzord/komiser/cmd.Commit={{ .ShortCommit }}
    mod_timestamp: '{{ .CommitTimestamp }}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates: ["ghcr.io/flemzord/komiser:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/flemzord/komiser
      - --label=org.opencontainers.image.source=https://github.com/flemzord/komiser
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates: ["ghcr.io/flemzord/komiser:{{ .Version }}-arm64"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/flemzord/komiser
      - --label=org.opencontainers.image.source=https://github.com/flemzord/komiser
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: ghcr.io/flemzord/komiser:{{ .Version }}
    image_templates:
      - ghcr.io/flemzord/komiser:{{ .Version }}-amd64
      - ghcr.io/flemzord/komiser:{{ .Version }}-arm64
  - name_template: ghcr.io/flemzord/komiser:latest
    image_templates:
      - ghcr.io/flemzord/komiser:{{ .Version }}-amd64
      - ghcr.io/flemzord/komiser:{{ .Version }}-arm64

brews:
  - tap:
      owner: flemzord
      name: homebrew-tap
    name: komiser
    folder: Formula
    skip_upload: false
    test: |
      system "#{bin}/komiser version"
    install: |
      bin.install "komiser"
