# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Komiser < Formula
  desc ""
  homepage ""
  version "0.1.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flemzord/komiser/releases/download/0.1.2/komiser_0.1.2_darwin_amd64.tar.gz"
      sha256 "b6347e2e0b1038d68394700a4feb065a492711d1488b6d0d16e672bf37bb2f4c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/flemzord/komiser/releases/download/0.1.2/komiser_0.1.2_darwin_arm64.tar.gz"
      sha256 "188d007815f0188ecbc00d92297adb2b869f390d4cbad1d9262f61ccd5249cd9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flemzord/komiser/releases/download/0.1.2/komiser_0.1.2_linux_amd64.tar.gz"
      sha256 "d0bf96b5fd1a13b57e7987ed68bf515266cbac868db862b49f62f4a0ce1935f9"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/flemzord/komiser/releases/download/0.1.2/komiser_0.1.2_linux_armv6.tar.gz"
      sha256 "b7f72bf3a4c5c73d4ab2ca1c4943b0d8bc61215e55516a5f07c907ba126e7a07"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flemzord/komiser/releases/download/0.1.2/komiser_0.1.2_linux_arm64.tar.gz"
      sha256 "a396f84b6a6315548d8b5b2a47a9ad29fe1bb9a5f52274eeae32e40e8eb94b7c"
    end
  end

  def install
    bin.install "komiser"
  end
end
