# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lsc < Formula
  desc ""
  homepage ""
  version "0.1.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flemzord/komiser/releases/download/0.1.1/komiser_0.1.1_darwin_amd64.tar.gz"
      sha256 "81b7d9b7f13584453fd7f0d97b04812133f466e9d6c80cf174eb2cdcb660fa98"
    end
    if Hardware::CPU.arm?
      url "https://github.com/flemzord/komiser/releases/download/0.1.1/komiser_0.1.1_darwin_arm64.tar.gz"
      sha256 "cb604a2977f75f0732d7a97a0668a7704a5952463e975493f211d9c0c09f8bab"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flemzord/komiser/releases/download/0.1.1/komiser_0.1.1_linux_amd64.tar.gz"
      sha256 "db37f68c76f7e327f310cdd4fbbd37ef7431949e5a5f0c0e60a47f0fbba70433"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/flemzord/komiser/releases/download/0.1.1/komiser_0.1.1_linux_armv6.tar.gz"
      sha256 "88a22c7f800b82d0667c7319d4f98d9919e25625a277dcb01a902278393ee675"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flemzord/komiser/releases/download/0.1.1/komiser_0.1.1_linux_arm64.tar.gz"
      sha256 "3eb28fbccb917dfb6ba5309895a00b438795aa95bd1207890ef7155498edbeda"
    end
  end

  def install
    bin.install "komiser"
  end
end
